added JsonStringLocalizer & added Sass dar
Veronneau-Techno-Conseil/comax-commons pull request #7
Opened 2022-05-24 23:45 UTC by saeb-panahifar

List of changes in this pull request.

1. Added JSON Based Localization 
2. Use Dart Sass instead of Sass

2022-05-25 13:35 UTC, vertechcon commented
Both translation files present in Client/Resources (the MainMenu ones) should be in ClientUI.Components/Shared

2022-05-25 13:44 UTC, vertechcon requested changes
Should move UI associated resources to ClientUI.Components and startup configuration into ClientUI.Shared so we can eventually support webasm mode

2022-05-25 13:44 UTC, vertechcon commented on Client/Program.cs
> +builder.Services.AddLocalization(options =>
To support webasm, this configuration should probably be set in ClientUI.Shared/Extensions/ServiceCollectionExtensions

2022-05-26 16:35 UTC, saeb-panahifar commented
> Both translation files present in Client/Resources (the MainMenu ones) should be in ClientUI.Components/Shared since they're associated with the MainMenu.razor file. This is so we can reuse those resource files when in webasm mode (note just in server mode).


Good point! I moved  `ClientUI/Resources` into `ClientUI.Components/Resources`. Should the resources be in one place (all JSON files in the resources folder) or beside the razor file?

2022-05-26 16:37 UTC, saeb-panahifar commented on Client/Resources/MainMenu-fr.json
> +  "About": "Sur"
Sorry, what does "À propos" means?

2022-05-26 16:52 UTC, vertechcon commented on Client/Resources/MainMenu-fr.json
> +  "About": "Sur"
It means "about", there are many different contextual expressions in french to say about something.  We use "À propos du...' or  "à propos de..." to introduce a subject but when nothing follows we just put "À propos". It mostly translates to "On the subject of...".  "Sur" would be used in a context like "I have nothing to say about this" => "Je n'ai rien à dire sur le sujet".

2022-05-26 16:53 UTC, vertechcon commented on Client/Resources/MainMenu-fr.json
> +  "About": "Sur"
For some reason i had the impression we could highlight code by selecting before adding comments... hmmm

2022-05-26 17:28 UTC, vertechcon commented
> In Resources folder (structure 2):
> * 📁 Resources
>   * 📁 MainMenu
>     * `en.json`
>     * `fr.json`

This approach looks pretty good actually! I didn't know we could use subfolders as type names! Makes things a lot cleaner.

2022-05-29 16:45 UTC, vertechcon approved these changes

2022-05-30 03:11 UTC, merged